spring:
  config:
    activate:
      on-profile:
        - dev
    use-legacy-processing: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/schema?serverTimezone=GMT%2B8
    username: root
    password: root
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8081
        port: 8719
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: database
      username: root
      password: password
      authentication-database: admin
    redis:
      host: 127.0.0.1
      port: 6379
      password: password
      database: 1
  devtools:
    add-properties: false
springdoc:
  api-docs:
    enabled: true
logging:
  level:
    web: info
# 自定义微信登录配置
wechat:
  appId: dev
  appSecret: dev
  grantType: authorization_code
file:
  prdOrWord: /upload
  picture: /upload



